package ba.test;
// Generated by ComTest BEGIN
import java.io.ByteArrayOutputStream;
import static org.junit.Assert.*;
import org.junit.*;
import static ba.Area.*;
import ba.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.03.31 13:21:50 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class AreaTest {



  // Generated by ComTest BEGIN
  /** testGetID45 */
  @Test
  public void testGetID45() {    // Area: 45
    Area a1 = new Area(); 
    a1.setAid(199); 
    assertEquals("From: Area line: 48", 199, a1.getID()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetLid60 */
  @Test
  public void testGetLid60() {    // Area: 60
    Area a1 = new Area(); 
    a1.setLid(199); 
    assertEquals("From: Area line: 63", 199, a1.getLid()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetName74 */
  @Test
  public void testGetName74() {    // Area: 74
    Area a = new Area().parse("10|Brodmann's Area 15|8"); 
    assertEquals("From: Area line: 76", "Brodmann's Area 15", a.getName()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse89 */
  @Test
  public void testParse89() {    // Area: 89
    Area area = new Area(); 
    area.parse(" 2 | Brodmann's Area 25 | 13 "); 
    assertEquals("From: Area line: 92", 2, area.getID()); 
    assertEquals("From: Area line: 93", 13, area.getLid()); 
    assertEquals("From: Area line: 94", "2|Brodmann's Area 25|13", area.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testPrint110 */
  @Test
  public void testPrint110() {    // Area: 110
    ByteArrayOutputStream outContent = new ByteArrayOutputStream(); 
    Area a = new Area().register().fillAreaInfo(); 
    a.print(outContent); 
    { String _l_=outContent.toString(),_r_="[0-9]+\\|Brodmann's\sArea\s[0-9]+\\|[0-9]+" + System.lineSeparator(); if ( !_l_.matches(_r_) ) fail("From: Area line: 115" + " does not match: ["+ _l_ + "] != [" + _r_ + "]");}; 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRegister129 */
  @Test
  public void testRegister129() {    // Area: 129
    Area a1 = new Area(); 
    Area a2 = new Area(); 
    assertEquals("From: Area line: 132", true, a1.register().getID() != -1); 
    assertEquals("From: Area line: 133", true, a2.register().getID() != a1.getID()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testSetAid148 */
  @Test
  public void testSetAid148() {    // Area: 148
    Area a1 = new Area(); 
    a1.setAid(199); 
    assertEquals("From: Area line: 151", 199, a1.getID()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testSetLid178 */
  @Test
  public void testSetLid178() {    // Area: 178
    assertEquals("From: Area line: 179", 1, new Area().setLid(1).getLid()); 
    assertEquals("From: Area line: 180", 3, new Area().setLid(3).getLid()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testSetNextAid193 */
  @Test
  public void testSetNextAid193() {    // Area: 193
    Area a1 = new Area(); 
    Area a2 = new Area(); 
    assertEquals("From: Area line: 196", true, a1.register().getID() != -1); 
    Area.setNextAid(2); 
    assertEquals("From: Area line: 198", 2, a2.register().getID()); 
  } // Generated by ComTest END
}