package ba.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static ba.Area.*;
import ba.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.03.14 13:10:13 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class AreaTest {



  // Generated by ComTest BEGIN
  /** testRegister27 */
  @Test
  public void testRegister27() {    // Area: 27
    Area a1 = new Area(); 
    Area a2 = new Area(); 
    assertEquals("From: Area line: 30", true, a1.register().getAid() != -1); 
    assertEquals("From: Area line: 31", true, a2.register().getAid() != a1.getAid()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testSetNextAid45 */
  @Test
  public void testSetNextAid45() {    // Area: 45
    Area a1 = new Area(); 
    Area a2 = new Area(); 
    assertEquals("From: Area line: 48", true, a1.register().getAid() != -1); 
    Area.setNextAid(2); 
    assertEquals("From: Area line: 50", 2, a2.register().getAid()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetAid61 */
  @Test
  public void testGetAid61() {    // Area: 61
    Area a1 = new Area(); 
    a1.setAid(199); 
    assertEquals("From: Area line: 64", 199, a1.getAid()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetLid85 */
  @Test
  public void testGetLid85() {    // Area: 85
    Area a1 = new Area(); 
    a1.setLid(199); 
    assertEquals("From: Area line: 88", 199, a1.getLid()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testSetLid107 */
  @Test
  public void testSetLid107() {    // Area: 107
    assertEquals("From: Area line: 108", 1, new Area().setLid(1).getLid()); 
    assertEquals("From: Area line: 109", 3, new Area().setLid(3).getLid()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testSetAid123 */
  @Test
  public void testSetAid123() {    // Area: 123
    Area a1 = new Area(); 
    a1.setAid(199); 
    assertEquals("From: Area line: 126", 199, a1.getAid()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse172 */
  @Test
  public void testParse172() {    // Area: 172
    Area area = new Area(); 
    area.parse(" 2 | Brodmann's Area 25 | 13 "); 
    assertEquals("From: Area line: 175", 2, area.getAid()); 
    assertEquals("From: Area line: 176", 13, area.getLid()); 
    assertEquals("From: Area line: 177", "2|Brodmann's Area 25|13", area.toString()); 
  } // Generated by ComTest END
}