package ba.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import ba.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.03.09 11:55:01 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class AreasTest {



  // Generated by ComTest BEGIN
  /** testAdd31 */
  @Test
  public void testAdd31() {    // Areas: 31
    Areas areas = new Areas(); 
    Area a1 = new Area(), a2 = new Area(); 
    assertEquals("From: Areas line: 34", 0, areas.getSize()); 
    areas.add(a1); assertEquals("From: Areas line: 35", 1, areas.getSize()); 
    areas.add(a2); assertEquals("From: Areas line: 36", 2, areas.getSize()); 
    areas.add(a1); assertEquals("From: Areas line: 37", 3, areas.getSize()); 
    assertEquals("From: Areas line: 38", a1, areas.get(0)); 
    assertEquals("From: Areas line: 39", a2, areas.get(1)); 
    assertEquals("From: Areas line: 40", a1, areas.get(2)); 
    assertEquals("From: Areas line: 41", false, areas.get(1) == a1); 
    assertEquals("From: Areas line: 42", true, areas.get(1) == a2); 
    try {
    assertEquals("From: Areas line: 43", a1, areas.get(3)); 
    fail("Areas: 43 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    areas.add(a1); assertEquals("From: Areas line: 44", 4, areas.getSize()); 
    areas.add(a1); assertEquals("From: Areas line: 45", 5, areas.getSize()); 
  } // Generated by ComTest END
}