package ba.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static ba.Area.*;
import ba.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.03.15 16:29:00 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class AreaTest {



  // Generated by ComTest BEGIN
  /** testGetID38 */
  @Test
  public void testGetID38() {    // Area: 38
    Area a1 = new Area(); 
    a1.setAid(199); 
    assertEquals("From: Area line: 41", 199, a1.getID()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetLid53 */
  @Test
  public void testGetLid53() {    // Area: 53
    Area a1 = new Area(); 
    a1.setLid(199); 
    assertEquals("From: Area line: 56", 199, a1.getLid()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetName67 */
  @Test
  public void testGetName67() {    // Area: 67
    Area a = new Area().parse("10|Brodmann's Area 15|8"); 
    assertEquals("From: Area line: 69", "Brodmann's Area 15", a.getName()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse82 */
  @Test
  public void testParse82() {    // Area: 82
    Area area = new Area(); 
    area.parse(" 2 | Brodmann's Area 25 | 13 "); 
    assertEquals("From: Area line: 85", 2, area.getID()); 
    assertEquals("From: Area line: 86", 13, area.getLid()); 
    assertEquals("From: Area line: 87", "2|Brodmann's Area 25|13", area.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRegister123 */
  @Test
  public void testRegister123() {    // Area: 123
    Area a1 = new Area(); 
    Area a2 = new Area(); 
    assertEquals("From: Area line: 126", true, a1.register().getID() != -1); 
    assertEquals("From: Area line: 127", true, a2.register().getID() != a1.getID()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testSetAid142 */
  @Test
  public void testSetAid142() {    // Area: 142
    Area a1 = new Area(); 
    a1.setAid(199); 
    assertEquals("From: Area line: 145", 199, a1.getID()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testSetLid159 */
  @Test
  public void testSetLid159() {    // Area: 159
    assertEquals("From: Area line: 160", 1, new Area().setLid(1).getLid()); 
    assertEquals("From: Area line: 161", 3, new Area().setLid(3).getLid()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testSetNextAid174 */
  @Test
  public void testSetNextAid174() {    // Area: 174
    Area a1 = new Area(); 
    Area a2 = new Area(); 
    assertEquals("From: Area line: 177", true, a1.register().getID() != -1); 
    Area.setNextAid(2); 
    assertEquals("From: Area line: 179", 2, a2.register().getID()); 
  } // Generated by ComTest END
}