package ba.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import ba.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.03.14 13:41:29 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class AreasTest {



  // Generated by ComTest BEGIN
  /** testAreas19 */
  @Test
  public void testAreas19() {    // Areas: 19
    Areas areas = new Areas(); 
    Area a1 = new Area(); 
    Area a2 = new Area(); 
    assertEquals("From: Areas line: 23", 0, areas.getSize()); 
    areas.add(a1); assertEquals("From: Areas line: 24", 1, areas.getSize()); 
    areas.add(a2); assertEquals("From: Areas line: 25", 2, areas.getSize()); 
    areas.add(a1); assertEquals("From: Areas line: 26", 3, areas.getSize()); 
    assertEquals("From: Areas line: 27", a1, areas.get(0)); 
    assertEquals("From: Areas line: 28", a2, areas.get(1)); 
    assertEquals("From: Areas line: 29", a1, areas.get(2)); 
    assertEquals("From: Areas line: 30", false, areas.get(1) == a1); 
    assertEquals("From: Areas line: 31", true, areas.get(1) == a2); 
    try {
    assertEquals("From: Areas line: 32", a1, areas.get(3)); 
    fail("Areas: 32 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    areas.add(a1); assertEquals("From: Areas line: 33", 4, areas.getSize()); 
    areas.add(a1); assertEquals("From: Areas line: 34", 5, areas.getSize()); 
  } // Generated by ComTest END
}