package ba.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static ba.Function.*;
import ba.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.03.14 17:54:50 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class FunctionTest {



  // Generated by ComTest BEGIN
  /** testRegister31 */
  @Test
  public void testRegister31() {    // Function: 31
    Function f1 = new Function(); 
    Function f2 = new Function(); 
    assertEquals("From: Function line: 34", true, f1.register().getFid() != -1); 
    assertEquals("From: Function line: 35", true, f2.register().getFid() != f1.getFid()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetFid54 */
  @Test
  public void testGetFid54() {    // Function: 54
    Function f1 = new Function(); 
    f1.setFid(199); 
    assertEquals("From: Function line: 57", 199, f1.getFid()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testSetNextFid69 */
  @Test
  public void testSetNextFid69() {    // Function: 69
    Function f1 = new Function(); 
    Function f2 = new Function(); 
    assertEquals("From: Function line: 72", true, f1.register().getFid() != -1); 
    Function.setNextFid(2); 
    assertEquals("From: Function line: 74", 2, f2.register().getFid()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testSetFid85 */
  @Test
  public void testSetFid85() {    // Function: 85
    Function f1 = new Function(); 
    f1.setFid(199); 
    assertEquals("From: Function line: 88", 199, f1.getFid()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetName99 */
  @Test
  public void testGetName99() {    // Function: 99
    Function f = new Function().parse("10|Grammar"); 
    assertEquals("From: Function line: 101", "Grammar", f.getName()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse141 */
  @Test
  public void testParse141() {    // Function: 141
    Function f = new Function(); 
    f.parse(" 2 | Localize pain"); 
    assertEquals("From: Function line: 144", 2, f.getFid()); 
    assertEquals("From: Function line: 145", "2|Localize pain", f.toString()); 
  } // Generated by ComTest END
}