package ba.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import ba.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.03.01 22:51:38 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class FunctionTest {


  // Generated by ComTest BEGIN
  /** testRegister38 */
  @Test
  public void testRegister38() {    // Function: 38
    Function f1 = new Function(); 
    Function f2 = new Function(); 
    assertEquals("From: Function line: 41", true, f1.register().getFid() != 0); 
    assertEquals("From: Function line: 42", true, f2.register().getFid() != f1.getFid()); 
  } // Generated by ComTest END
}