package ba.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import ba.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.03.09 13:09:18 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class FunctionsTest {



  // Generated by ComTest BEGIN
  /** testAdd17 */
  @Test
  public void testAdd17() {    // Functions: 17
    Functions functions = new Functions(); 
    Function a1 = new Function(), a2 = new Function(); 
    assertEquals("From: Functions line: 20", 0, functions.getSize()); 
    functions.add(a1); assertEquals("From: Functions line: 21", 1, functions.getSize()); 
    functions.add(a2); assertEquals("From: Functions line: 22", 2, functions.getSize()); 
    functions.add(a1); assertEquals("From: Functions line: 23", 3, functions.getSize()); 
    assertEquals("From: Functions line: 24", a1, functions.get(0)); 
    assertEquals("From: Functions line: 25", a2, functions.get(1)); 
    assertEquals("From: Functions line: 26", a1, functions.get(2)); 
    assertEquals("From: Functions line: 27", false, functions.get(1) == a1); 
    assertEquals("From: Functions line: 28", true, functions.get(1) == a2); 
    functions.add(a1); assertEquals("From: Functions line: 29", 4, functions.getSize()); 
    functions.add(a1); assertEquals("From: Functions line: 30", 5, functions.getSize()); 
  } // Generated by ComTest END
}