package ba.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static ba.Function.*;
import ba.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.03.15 16:29:17 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class FunctionTest {



  // Generated by ComTest BEGIN
  /** testGetID40 */
  @Test
  public void testGetID40() {    // Function: 40
    Function f1 = new Function(); 
    f1.setFid(199); 
    assertEquals("From: Function line: 43", 199, f1.getID()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetName55 */
  @Test
  public void testGetName55() {    // Function: 55
    Function f = new Function().parse("10|Grammar"); 
    assertEquals("From: Function line: 57", "Grammar", f.getName()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse70 */
  @Test
  public void testParse70() {    // Function: 70
    Function f = new Function(); 
    f.parse(" 2 | Localize pain"); 
    assertEquals("From: Function line: 73", 2, f.getID()); 
    assertEquals("From: Function line: 74", "2|Localize pain", f.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRegister106 */
  @Test
  public void testRegister106() {    // Function: 106
    Function f1 = new Function(); 
    Function f2 = new Function(); 
    assertEquals("From: Function line: 109", true, f1.register().getID() != -1); 
    assertEquals("From: Function line: 110", true, f2.register().getID() != f1.getID()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testSetFid124 */
  @Test
  public void testSetFid124() {    // Function: 124
    Function f1 = new Function(); 
    f1.setFid(199); 
    assertEquals("From: Function line: 127", 199, f1.getID()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testSetNextFid140 */
  @Test
  public void testSetNextFid140() {    // Function: 140
    Function f1 = new Function(); 
    Function f2 = new Function(); 
    assertEquals("From: Function line: 143", true, f1.register().getID() != -1); 
    Function.setNextFid(2); 
    assertEquals("From: Function line: 145", 2, f2.register().getID()); 
  } // Generated by ComTest END
}