package ba.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import ba.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.03.23 15:00:37 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class FunctionsTest {


  // Generated by ComTest BEGIN
  /** 
   * testFunctions10 
   * @throws TilaException when error
   */
  @Test
  public void testFunctions10() throws TilaException {    // Functions: 10
    Functions functions = new Functions(); 
    Function a1 = new Function().setName("AA"), a2 = new Function().setName("AB"); 
    assertEquals("From: Functions line: 14", 0, functions.getSize()); 
    functions.add(a1); assertEquals("From: Functions line: 15", 1, functions.getSize()); 
    functions.add(a2); assertEquals("From: Functions line: 16", 2, functions.getSize()); 
    assertEquals("From: Functions line: 17", a1, functions.get(0)); 
    assertEquals("From: Functions line: 18", a2, functions.get(1)); 
    assertEquals("From: Functions line: 19", false, functions.get(1) == a1); 
    assertEquals("From: Functions line: 20", true, functions.get(1) == a2); 
    functions.add(new Function().setName("BB")); assertEquals("From: Functions line: 21", 3, functions.getSize()); 
    functions.add(new Function().setName("CC")); assertEquals("From: Functions line: 22", 4, functions.getSize()); 
  } // Generated by ComTest END
}