package ba.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import ba.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.03.14 17:57:09 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class FunctionsTest {



  // Generated by ComTest BEGIN
  /** testFunctions13 */
  @Test
  public void testFunctions13() {    // Functions: 13
    Functions functions = new Functions(); 
    Function a1 = new Function(), a2 = new Function(); 
    assertEquals("From: Functions line: 16", 0, functions.getSize()); 
    functions.add(a1); assertEquals("From: Functions line: 17", 1, functions.getSize()); 
    functions.add(a2); assertEquals("From: Functions line: 18", 2, functions.getSize()); 
    functions.add(a1); assertEquals("From: Functions line: 19", 3, functions.getSize()); 
    assertEquals("From: Functions line: 20", a1, functions.get(0)); 
    assertEquals("From: Functions line: 21", a2, functions.get(1)); 
    assertEquals("From: Functions line: 22", a1, functions.get(2)); 
    assertEquals("From: Functions line: 23", false, functions.get(1) == a1); 
    assertEquals("From: Functions line: 24", true, functions.get(1) == a2); 
    functions.add(a1); assertEquals("From: Functions line: 25", 4, functions.getSize()); 
    functions.add(a1); assertEquals("From: Functions line: 26", 5, functions.getSize()); 
  } // Generated by ComTest END
}