package ba.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import ba.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.03.01 23:34:13 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class LocationsTest {



  // Generated by ComTest BEGIN
  /** 
   * testAdd24 
   * @throws TilaException when error
   */
  @Test
  public void testAdd24() throws TilaException {    // Locations: 24
    Locations locations = new Locations(); 
    Location a1 = new Location(), a2 = new Location(); 
    assertEquals("From: Locations line: 28", 0, locations.getSize()); 
    locations.add(a1); assertEquals("From: Locations line: 29", 1, locations.getSize()); 
    locations.add(a2); assertEquals("From: Locations line: 30", 2, locations.getSize()); 
    locations.add(a1); assertEquals("From: Locations line: 31", 3, locations.getSize()); 
    assertEquals("From: Locations line: 32", a1, locations.get(0)); 
    assertEquals("From: Locations line: 33", a2, locations.get(1)); 
    assertEquals("From: Locations line: 34", a1, locations.get(2)); 
    assertEquals("From: Locations line: 35", false, locations.get(1) == a1); 
    assertEquals("From: Locations line: 36", true, locations.get(1) == a2); 
    try {
    assertEquals("From: Locations line: 37", a1, locations.get(3)); 
    fail("Locations: 37 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    locations.add(a1); assertEquals("From: Locations line: 38", 4, locations.getSize()); 
    locations.add(a1); assertEquals("From: Locations line: 39", 5, locations.getSize()); 
    try {
    locations.add(a1); 
    fail("Locations: 40 Did not throw TilaException");
    } catch(TilaException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END
}