package ba.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static ba.Location.*;
import ba.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.03.15 16:29:24 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class LocationTest {



  // Generated by ComTest BEGIN
  /** testGetID40 */
  @Test
  public void testGetID40() {    // Location: 40
    Location l1 = new Location(); 
    l1.setLid(199); 
    assertEquals("From: Location line: 43", 199, l1.getID()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetName55 */
  @Test
  public void testGetName55() {    // Location: 55
    Location l = new Location().parse("10|Secondary motor cortex"); 
    assertEquals("From: Location line: 57", "Secondary motor cortex", l.getName()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse70 */
  @Test
  public void testParse70() {    // Location: 70
    Location l = new Location(); 
    l.parse(" 7 | Temporal lobe "); 
    assertEquals("From: Location line: 73", 7, l.getID()); 
    assertEquals("From: Location line: 74", "7|Temporal lobe", l.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRegister106 */
  @Test
  public void testRegister106() {    // Location: 106
    Location a1 = new Location(); 
    Location a2 = new Location(); 
    assertEquals("From: Location line: 109", true, a1.register().getID() != -1); 
    assertEquals("From: Location line: 110", true, a2.register().getID() != a1.getID()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testSetLid125 */
  @Test
  public void testSetLid125() {    // Location: 125
    Location l1 = new Location(); 
    l1.setLid(199); 
    assertEquals("From: Location line: 128", 199, l1.getID()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testSetNextLid141 */
  @Test
  public void testSetNextLid141() {    // Location: 141
    Location l1 = new Location(); 
    Location l2 = new Location(); 
    assertEquals("From: Location line: 144", true, l1.register().getID() != -1); 
    Location.setNextLid(2); 
    assertEquals("From: Location line: 146", 2, l2.register().getID()); 
  } // Generated by ComTest END
}