package ba.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import ba.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.03.14 18:16:50 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class LocationsTest {



  // Generated by ComTest BEGIN
  /** testLocations17 */
  @Test
  public void testLocations17() {    // Locations: 17
    Locations locations = new Locations(); 
    Location a1 = new Location(), a2 = new Location(); 
    assertEquals("From: Locations line: 20", 0, locations.getSize()); 
    locations.add(a1); assertEquals("From: Locations line: 21", 1, locations.getSize()); 
    locations.add(a2); assertEquals("From: Locations line: 22", 2, locations.getSize()); 
    locations.add(a1); assertEquals("From: Locations line: 23", 3, locations.getSize()); 
    assertEquals("From: Locations line: 24", a1, locations.get(0)); 
    assertEquals("From: Locations line: 25", a2, locations.get(1)); 
    assertEquals("From: Locations line: 26", a1, locations.get(2)); 
    assertEquals("From: Locations line: 27", false, locations.get(1) == a1); 
    assertEquals("From: Locations line: 28", true, locations.get(1) == a2); 
    try {
    assertEquals("From: Locations line: 29", a1, locations.get(3)); 
    fail("Locations: 29 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    locations.add(a1); assertEquals("From: Locations line: 30", 4, locations.getSize()); 
    locations.add(a1); assertEquals("From: Locations line: 31", 5, locations.getSize()); 
  } // Generated by ComTest END
}