package ba.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static ba.Location.*;
import ba.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.03.14 18:15:29 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class LocationTest {



  // Generated by ComTest BEGIN
  /** testGetName29 */
  @Test
  public void testGetName29() {    // Location: 29
    Location l = new Location().parse("10|Secondary motor cortex"); 
    assertEquals("From: Location line: 31", "Secondary motor cortex", l.getName()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testSetNextLid43 */
  @Test
  public void testSetNextLid43() {    // Location: 43
    Location l1 = new Location(); 
    Location l2 = new Location(); 
    assertEquals("From: Location line: 46", true, l1.register().getLid() != -1); 
    Location.setNextLid(2); 
    assertEquals("From: Location line: 48", 2, l2.register().getLid()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetLid59 */
  @Test
  public void testGetLid59() {    // Location: 59
    Location l1 = new Location(); 
    l1.setLid(199); 
    assertEquals("From: Location line: 62", 199, l1.getLid()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testSetLid74 */
  @Test
  public void testSetLid74() {    // Location: 74
    Location l1 = new Location(); 
    l1.setLid(199); 
    assertEquals("From: Location line: 77", 199, l1.getLid()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRegister89 */
  @Test
  public void testRegister89() {    // Location: 89
    Location a1 = new Location(); 
    Location a2 = new Location(); 
    assertEquals("From: Location line: 92", true, a1.register().getLid() != -1); 
    assertEquals("From: Location line: 93", true, a2.register().getLid() != a1.getLid()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse131 */
  @Test
  public void testParse131() {    // Location: 131
    Location l = new Location(); 
    l.parse(" 7 | Temporal lobe "); 
    assertEquals("From: Location line: 134", 7, l.getLid()); 
    assertEquals("From: Location line: 135", "7|Temporal lobe", l.toString()); 
  } // Generated by ComTest END
}